#%RAML 1.0 DataType
type: object
properties:
  id:
    type: string | nil
    required: false
  numero:
    type: string | nil
    required: false
  descricao:
    type: string | nil
    required: false
  status:
    type: string | nil
    required: false
  dtCriacao:
    type: string | nil
    required: false
  unidadeOrganizacional:
    type: string | nil
    required: false
  grupo:
    type: string | nil
    required: false
  tag:
    type: string | nil
    required: false
  documento:
    type: string | nil
    required: false
  url:
    type: string | nil
    required: false
  qtdPendencias:
    type: string | nil
    required: false