#%RAML 1.0 DataType
type: object
properties:
  entrada:
    type: object
    properties:
      sistemaOrigem:
        type: string | nil
        required: false
      sistemaDestino:
        type: string | nil
        required: false
      usuarioLogado:
        type: string | nil
        required: false
      dataInicioProcessamento:
        type: string | nil
        required: false
      tempoMaxEspera:
        type: string | nil
        required: false
      servico:
        type: string | nil
        required: false
      pagina:
        type: string | nil
        required: false
      qtdMaxRegistros:
        type: string | nil
        required: false
      parametros:
        type: array
        items: !include /data-types/imports/entry.raml
        required: true